export const Cards = [
  {
    _id: "64de5113a05102006c172309",
    eoDate: "2024-01-12T18:30:00.000Z",
    registrationfee: 200,
    startTime: "2024-01-13T12:35:00.000Z",
    endTime: "2024-01-13T12:35:00.000Z",
    Image: [],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695978005516.jpeg",
    totalslot: 57,
    name: " Victoria Memorial",
    whatInclude:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    whattoBring:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    whattoExpect:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    meetingPoint:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    cancPolicy:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    addInfo:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    description:
      "The Victoria Memorial is a large marble building on the Maidan in Central Kolkata, having its entrance on the Queen's Way",
    mystatus: 1,
    mywaitstatus: 0,
  },
  {
    _id: "6513ee35efb2e37b6aa9e862",
    eoDate: "2024-01-12T18:30:00.000Z",
    registrationfee: 200,
    startTime: "2024-01-13T12:35:00.000Z",
    endTime: "2024-01-13T12:35:00.000Z",
    Image: [
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695727526452.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695727527358.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695727527508.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695727527565.jpeg",
    ],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695727527358.jpeg",
    totalslot: 0,
    name: " Test Victoria Memorial",
    whatInclude:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    whattoBring:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    whattoExpect:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    meetingPoint:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    cancPolicy:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    addInfo:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    description:
      "The Victoria Memorial is a large marble building on the Maidan in Central Kolkata, having its entrance on the Queen's Way",
    mystatus: 0,
    mywaitstatus: 1,
  },
  {
    _id: "65080fa538524300679ef4d1",
    eoDate: "2024-01-11T08:27:58.000Z",
    registrationfee: 1500,
    startTime: "2024-01-11T08:27:00.000Z",
    endTime: "2024-01-11T09:27:00.000Z",
    Image: [
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695982948579.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695982950497.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695982950683.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695982950801.jpeg",
    ],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695983032031.jpeg",
    totalslot: 496,
    name: "Eden Gardens",
    whatInclude: "Eden Gardens",
    whattoBring: "Eden Gardens",
    whattoExpect: "Eden Gardens",
    meetingPoint: "Eden Gardens",
    cancPolicy: "Eden Gardens",
    addInfo: "Eden Gardens",
    description: "Eden Gardens",
    mystatus: 1,
    mywaitstatus: 0,
  },
  {
    _id: "6516a62634c0c64c5214e8fa",
    eoDate: "2024-01-11T08:27:58.000Z",
    registrationfee: 1500,
    startTime: "2024-01-11T08:30:00.000Z",
    endTime: "2024-01-11T10:30:00.000Z",
    Image: [
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695982948579.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695982950497.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695982950683.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695982950801.jpeg",
    ],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695983032031.jpeg",
    totalslot: 493,
    name: "Eric Randolph",
    whatInclude: "Eden Gardens",
    whattoBring: "Eden Gardens",
    whattoExpect: "Eden Gardens",
    meetingPoint: "Eden Gardens",
    cancPolicy: "Eden Gardens",
    addInfo: "Eden Gardens",
    description: "Eden Gardens",
    mystatus: 0,
    mywaitstatus: 0,
  },
  {
    _id: "6516822a8a8af60069cb7de8",
    eoDate: "2024-01-11T00:00:00.000Z",
    registrationfee: 2000,
    startTime: "2024-01-11T04:49:00.000Z",
    endTime: "2024-01-11T05:49:00.000Z",
    Image: [
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695973930465.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695973931379.jpeg",
    ],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1695973931446.jpeg",
    totalslot: 197,
    name: "Barrett Mckee",
    whatInclude: "Eiusmod et cillum vo",
    whattoBring: "Consectetur animi f",
    whattoExpect: "Mollit in dolorem ea",
    meetingPoint: "Consequatur est quia",
    cancPolicy: "Voluptate vitae ut p",
    addInfo: "Soluta cupiditate cu",
    description: "Ex facere quod et sa",
    mystatus: 1,
    mywaitstatus: 0,
  },
  {
    _id: "651a7f85b259f7006e9da198",
    eoDate: "2024-01-11T00:00:00.000Z",
    registrationfee: 7000,
    startTime: "2024-01-11T07:21:00.000Z",
    endTime: "2024-01-11T09:21:00.000Z",
    Image: [
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696235397984.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696235398071.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696235398086.jpeg",
    ],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696235398107.jpeg",
    totalslot: 69,
    name: "Demo Mayapur",
    whatInclude: "Demo Text Goes Here",
    whattoBring: "Demo Text Goes Here",
    whattoExpect: "Demo Text Goes Here",
    meetingPoint: "Demo Text Goes Here",
    cancPolicy: "Demo Text Goes Here",
    addInfo: "Demo Text Goes Here",
    description: "Demo Text Goes Here",
    mystatus: 0,
    mywaitstatus: 0,
  },
  {
    _id: "651a9e0e2cb18100681d860f",
    eoDate: "2024-01-10T18:30:00.000Z",
    registrationfee: 3000,
    startTime: "2024-01-11T10:00:00.000Z",
    endTime: "2024-01-11T13:00:00.000Z",
    Image: [
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696243214026.jpeg",
    ],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696243214770.jpeg",
    totalslot: 28,
    name: "MyEO Ganga Aarti with Shikara ride",
    whatInclude: 'Lifejacket\nLogistics from ITC and Back"\n',
    whattoBring:
      "Please wear comfortable shoes as you may have to walk on wet surfaces\n",
    whattoExpect: "Culture, Leisure\n",
    meetingPoint: "ITC Royal Bengal Reception Lounge\n",
    cancPolicy: "Please refer to the FAQs on the main website\n",
    addInfo: "Champion- Aditya Manaksia- 9830684026\n",
    description:
      '"Immerse yourself in the spiritual Ganga Aarti and soulful live folk music on the sacred Ganges over an unforgettable two-hour cruise tour simultaneously, experiencing mouth watering live snacks and sipping tea in kullars, to relish the true flavour of the region and the essence of local culture along with viewing numerous facets, historical and religious sights of THE CITY OF JOY! \nTake in historic sights on the banks of the River Hooghly and see how the river has played a pivotal role in shaping the culture and heritage of our City."\n',
    mystatus: 1,
    mywaitstatus: 0,
  },
  {
    _id: "651bb55057764a31ec6cee2e",
    eoDate: null,
    registrationfee: 6000,
    startTime: "2024-01-10T01:00:00.000Z",
    endTime: "2024-01-10T02:00:00.000Z",
    Image: [
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696314704145.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696314704864.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696314705062.jpeg",
    ],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696314705211.jpeg",
    totalslot: 400,
    name: "Joy Summers",
    whatInclude: "Inventore quod est t",
    whattoBring: "Dicta quasi esse par",
    whattoExpect: "Nostrum quo placeat",
    meetingPoint: "Nostrum quo placeat",
    cancPolicy: "Nostrum quo placeat",
    addInfo: "Nostrum quo placeat",
    description: "Et vero id obcaecati",
    mystatus: 0,
    mywaitstatus: 0,
  },
  {
    _id: "651bb953106ac7006c32de9d",
    eoDate: null,
    registrationfee: 6000,
    startTime: "2024-01-10T06:00:00.000Z",
    endTime: "2024-01-12T07:00:00.000Z",
    Image: [
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696315731931.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696315732736.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696315732817.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696315732867.jpeg",
    ],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696315732905.jpeg",
    totalslot: 200,
    name: "Zoe Barry",
    whatInclude: "",
    whattoBring: "",
    whattoExpect: "",
    meetingPoint: "",
    cancPolicy: "",
    addInfo: "",
    description: "",
    mystatus: 0,
    mywaitstatus: 0,
  },
  {
    _id: "651bbaf8106ac7006c32ec37",
    eoDate: null,
    registrationfee: 3000,
    startTime: "2024-01-12T05:00:00.000Z",
    endTime: "2024-01-13T19:00:00.000Z",
    Image: [
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696316153687.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696316156876.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696316159360.jpeg",
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696316159424.jpeg",
    ],
    thumb_image:
      "https://riekolstorageaccount.blob.core.windows.net/eocontainer/1696316159468.jpeg",
    totalslot: 20,
    name: "Jacob Woodard",
    whatInclude: "",
    whattoBring: "",
    whattoExpect: "",
    meetingPoint: "",
    cancPolicy: "",
    addInfo: "",
    description: "",
    mystatus: 0,
    mywaitstatus: 0,
  },
];
